### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by Na7hanie1** [Wind-Development/WindSpigot#63]
**Describe the bug**
Unknown error. Players cannot attack each other. The console keeps reporting errors, and then the server crashes

**Bug on latest**
yes

**To Reproduce**
[16:15:29] [Server thread/INFO]: [AAC5] Detected 1.8.x for 8awa8
[16:15:33] [nioEventLoopGroup-3-7/WARN]: java.lang.IllegalStateException: PacketSendEvent cannot be triggered asynchronously from inside synchronized code.
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at dev._2lstudios.hamsterapi.handlers.HamsterChannelHandler.write(HamsterChannelHandler.java:33)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:137)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:117)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)

**Comment by Na7hanie1** [comment]
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:131)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:131)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:88)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.dispatchPacket(NetworkManager.java:293)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:237)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:1193)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at cn.charlotte.pit.util.chat.ActionBarUtil.sendActionBar(ActionBarUtil.java:20)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at cn.charlotte.pit.game.listener.CombatListener.handleDamage(CombatListener.java:287)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at cn.charlotte.pit.game.listener.CombatListener.onCombat(CombatListener.java:156)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:168)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:670)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:574)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:707)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1217)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:910)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:793)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:849)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:562)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1066)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1198)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1710)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:39)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:7)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:203)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:544)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:44)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.channelRead(BukkitPipelineInjector.java:59)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:142)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at eu.decentsoftware.holograms.api.nms.PacketHandler.channelRead(PacketHandler.java:60)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[16:15:33] [nioEventLoopGroup-3-7/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:142)

**Comment by ghost** [comment]
It’s looks like HamsterAPI is trying to run an async event synced, not a WindSpigot issue. Report it to them.

**Comment by windcolor-dev** [comment]
Are you on the latest release? I think this was fixed in the 2.1.2-hotfix version.

**Comment by windcolor-dev** [comment]
> It’s looks like HamsterAPI is trying to run an async event synced, not a WindSpigot issue. Report it to them.

I don't think its a problem with that plugin, WindSpigot versions 2.1.2 and under reported parallel world threads as non main threads, which led to custom events being async.

**Comment by Na7hanie1** [comment]
> 

Yes, I use the 2.1.2hotfix version, but the problem still exists

**Comment by windcolor-dev** [comment]
Does this occur on PaperSpigot?
